// Public ANN snapshots retained unchanged from alias-candidate-public-snapshots.json,
// historical 2026-10-06T14:21:41Z. No live IDs, private rows, or product contents.
// Two dots keep this fixture out of Convex deployment.
import type { AnnReleaseSnapshot } from "./ann";

export const sailorMoon = {
  source: {
    annId: "19983",
    date: {
      day: 10,
      month: 7,
      year: 2012,
    },
    editionLineHint: false,
    format: "physical",
    isbn13: "9781612620022",
    kind: "annRelease",
    label: "6",
    mangaId: "1578",
    multi: false,
    page: {
      date: {
        day: 10,
        month: 7,
        year: 2012,
      },
      distributor: "Kodansha Comics",
      distributorId: "8388",
      fetchedAt: 1790490722909,
      isbn10: "1612620027",
      isbn13: "9781612620022",
      mangaId: "1578",
      priceCents: 1099,
      status: "ok",
      title: "Pretty Guardian Sailor Moon",
      volume: "GN 6 / 12",
    },
    title: "Pretty Guardian Sailor Moon",
    url: "https://www.animenewsnetwork.com/encyclopedia/releases.php?id=19983",
  } satisfies AnnReleaseSnapshot,
  parent: {
    altTitles: [
      "Bishōjo Senshi Sailor Moon",
      "Pretty Guardian Sailor Moon",
      "美少女戦士セーラームーン",
    ],
    credits: [
      {
        name: "Naoko Takeuchi",
        personId: "82",
        task: "Story & Art",
      },
    ],
    id: "1578",
    kind: "annManga",
    releases: [
      {
        annId: "40058",
        date: {
          day: 1,
          month: 7,
          year: 2019,
        },
        editionLineHint: false,
        format: "digital",
        isbn13: "9781642129335",
        label: "1",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40060",
        date: {
          day: 1,
          month: 7,
          year: 2019,
        },
        editionLineHint: false,
        format: "digital",
        isbn13: "9781642129342",
        label: "2",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40075",
        date: {
          day: 1,
          month: 7,
          year: 2019,
        },
        editionLineHint: false,
        format: "digital",
        isbn13: "9781642129359",
        label: "3",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40076",
        date: {
          day: 1,
          month: 7,
          year: 2019,
        },
        editionLineHint: false,
        format: "digital",
        isbn13: "9781642129403",
        label: "4",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40064",
        date: {
          day: 15,
          month: 10,
          year: 2019,
        },
        editionLineHint: false,
        format: "digital",
        isbn13: "9781642129991",
        label: "5",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40077",
        date: {
          day: 12,
          month: 11,
          year: 2019,
        },
        editionLineHint: false,
        format: "digital",
        isbn13: "9781646590001",
        label: "6",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40078",
        date: {
          day: 7,
          month: 7,
          year: 2020,
        },
        editionLineHint: false,
        format: "digital",
        isbn13: "9781646590018",
        label: "7",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40079",
        date: {
          day: 14,
          month: 7,
          year: 2020,
        },
        editionLineHint: false,
        format: "digital",
        isbn13: "9781646594719",
        label: "8",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40069",
        date: {
          day: 17,
          month: 11,
          year: 2020,
        },
        editionLineHint: false,
        format: "digital",
        isbn13: "9781646595792",
        label: "9",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40071",
        date: {
          day: 17,
          month: 11,
          year: 2020,
        },
        editionLineHint: false,
        format: "digital",
        isbn13: "9781646598397",
        label: "10",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "18812",
        date: {
          day: 13,
          month: 9,
          year: 2011,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781935429746",
        label: "1",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "18814",
        date: {
          day: 15,
          month: 11,
          year: 2011,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781935429753",
        label: "2",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "18816",
        date: {
          day: 17,
          month: 1,
          year: 2012,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781935429760",
        label: "3",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "18817",
        date: {
          day: 13,
          month: 3,
          year: 2012,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612620008",
        label: "4",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "18818",
        date: {
          day: 8,
          month: 5,
          year: 2012,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612620015",
        label: "5",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "19983",
        date: {
          day: 10,
          month: 7,
          year: 2012,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612620022",
        label: "6",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "20187",
        date: {
          day: 11,
          month: 9,
          year: 2012,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612620039",
        label: "7",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "20553",
        date: {
          day: 30,
          month: 10,
          year: 2012,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612620046",
        label: "8",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "20757",
        date: {
          day: 29,
          month: 1,
          year: 2013,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612620053",
        label: "9",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "21068",
        date: {
          day: 19,
          month: 3,
          year: 2013,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612620060",
        label: "10",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "22381",
        date: {
          day: 7,
          month: 5,
          year: 2013,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612620077",
        label: "11",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "22382",
        date: {
          day: 2,
          month: 7,
          year: 2013,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612620084",
        label: "12",
        multi: false,
        title: "Pretty Guardian Sailor Moon",
      },
      {
        annId: "21950",
        coverRange: {
          from: "1",
          to: "6",
        },
        date: {
          day: 20,
          month: 11,
          year: 2012,
        },
        editionLineHint: true,
        format: "physical",
        isbn13: "9781612623962",
        multi: true,
        title: "Pretty Guardian Sailor Moon - Box Set 1",
      },
      {
        annId: "23395",
        coverRange: {
          from: "7",
          to: "12",
        },
        date: {
          day: 29,
          month: 10,
          year: 2013,
        },
        editionLineHint: true,
        format: "physical",
        isbn13: "9781612623979",
        multi: true,
        title: "Pretty Guardian Sailor Moon - Box Set 2",
      },
      {
        annId: "40057",
        date: {
          day: 11,
          month: 9,
          year: 2018,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781632361523",
        label: "1",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40059",
        date: {
          day: 13,
          month: 11,
          year: 2018,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781632361530",
        label: "2",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40061",
        date: {
          day: 19,
          month: 3,
          year: 2019,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781632361547",
        label: "3",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40062",
        date: {
          day: 14,
          month: 5,
          year: 2019,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781632361554",
        label: "4",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40063",
        date: {
          day: 25,
          month: 6,
          year: 2019,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781632361561",
        label: "5",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40065",
        date: {
          day: 12,
          month: 11,
          year: 2019,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781632365934",
        label: "6",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40066",
        date: {
          day: 21,
          month: 1,
          year: 2020,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781632365941",
        label: "7",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40067",
        date: {
          day: 24,
          month: 3,
          year: 2020,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781632365958",
        label: "8",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40068",
        date: {
          day: 8,
          month: 9,
          year: 2020,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781632365965",
        label: "9",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "40070",
        date: {
          day: 20,
          month: 10,
          year: 2020,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781632365972",
        label: "10",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Eternal Edition]",
      },
      {
        annId: "46305",
        date: {
          day: 7,
          month: 6,
          year: 2022,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646512140",
        label: "2",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection]",
      },
      {
        annId: "46306",
        date: {
          day: 2,
          month: 8,
          year: 2022,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646512461",
        label: "3",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection]",
      },
      {
        annId: "46307",
        date: {
          day: 19,
          month: 9,
          year: 2023,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646512560",
        label: "4",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection]",
      },
      {
        annId: "46308",
        date: {
          day: 28,
          month: 11,
          year: 2023,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646512577",
        label: "5",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection]",
      },
      {
        annId: "50067",
        date: {
          day: 30,
          month: 1,
          year: 2024,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646513697",
        label: "6",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection]",
      },
      {
        annId: "50068",
        date: {
          day: 19,
          month: 3,
          year: 2024,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646513703",
        label: "7",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection]",
      },
      {
        annId: "50069",
        date: {
          day: 21,
          month: 5,
          year: 2024,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646513710",
        label: "8",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection]",
      },
      {
        annId: "50070",
        date: {
          day: 23,
          month: 7,
          year: 2024,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646513727",
        label: "9",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection]",
      },
      {
        annId: "50071",
        date: {
          day: 17,
          month: 9,
          year: 2024,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646513734",
        label: "10",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection]",
      },
      {
        annId: "40074",
        date: {
          day: 3,
          month: 5,
          year: 2022,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646512010",
        label: "1",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection]",
      },
      {
        annId: "43286",
        date: {
          day: 3,
          month: 5,
          year: 2022,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646516803",
        label: "1",
        multi: false,
        title: "Pretty Guardian Sailor Moon [Naoko Takeuchi Collection] [B&N Exclusive]",
      },
      {
        annId: "24566",
        date: {
          day: 10,
          month: 9,
          year: 2013,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612624426",
        label: "1",
        multi: false,
        title: "Pretty Guardian Sailor Moon Short Stories",
      },
      {
        annId: "24567",
        date: {
          day: 26,
          month: 11,
          year: 2013,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781612620107",
        label: "2",
        multi: false,
        title: "Pretty Guardian Sailor Moon Short Stories",
      },
      {
        annId: "46309",
        date: {
          day: 14,
          month: 2,
          year: 2023,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781646517541",
        label: "1",
        multi: false,
        title:
          "Pretty Guardian Sailor Moon with Exclusive Q Posket Petit Figure [Naoko Takeuchi Collection]",
      },
      {
        annId: "4737",
        date: {
          month: 12,
          year: 1998,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213013",
        label: "1",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "20404",
        date: {
          day: 24,
          month: 12,
          year: 1998,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213051",
        label: "2",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "20405",
        date: {
          day: 21,
          month: 5,
          year: 1999,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213068",
        label: "3",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "20471",
        date: {
          day: 14,
          month: 9,
          year: 1999,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213150",
        label: "4",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "20472",
        date: {
          day: 28,
          month: 9,
          year: 1999,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213204",
        label: "5",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "20473",
        date: {
          day: 8,
          month: 2,
          year: 2000,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213358",
        label: "6",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "20474",
        date: {
          day: 6,
          month: 6,
          year: 2000,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213426",
        label: "7",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "20475",
        date: {
          day: 5,
          month: 12,
          year: 2000,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213471",
        label: "8",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "20476",
        date: {
          day: 17,
          month: 4,
          year: 2001,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213686",
        label: "9",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "20477",
        date: {
          day: 10,
          month: 7,
          year: 2001,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213983",
        label: "10",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "20478",
        date: {
          day: 15,
          month: 10,
          year: 2001,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213990",
        label: "11",
        multi: false,
        title: "Sailor Moon",
      },
      {
        annId: "50073",
        coverRange: {
          from: "1",
          to: "6",
        },
        date: {
          day: 12,
          month: 11,
          year: 2024,
        },
        editionLineHint: true,
        format: "physical",
        isbn13: "9798888773390",
        multi: true,
        title: "Sailor Moon - Box Set 1 [Naoko Takeuchi Collection]",
      },
      {
        annId: "56014",
        coverRange: {
          from: "7",
          to: "10",
        },
        date: {
          day: 9,
          month: 12,
          year: 2025,
        },
        editionLineHint: true,
        format: "physical",
        isbn13: "9798888773406",
        multi: true,
        title: "Sailor Moon - Box Set 2 [Naoko Takeuchi Collection]",
      },
      {
        annId: "20483",
        date: {
          day: 13,
          month: 3,
          year: 2001,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213488",
        label: "1",
        multi: false,
        title: "Sailor Moon Stars",
      },
      {
        annId: "20484",
        date: {
          day: 19,
          month: 6,
          year: 2001,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213709",
        label: "2",
        multi: false,
        title: "Sailor Moon Stars",
      },
      {
        annId: "20485",
        date: {
          day: 18,
          month: 9,
          year: 2001,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213976",
        label: "3",
        multi: false,
        title: "Sailor Moon Stars",
      },
      {
        annId: "20479",
        date: {
          day: 16,
          month: 3,
          year: 1999,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213129",
        label: "1",
        multi: false,
        title: "Sailor Moon SuperS",
      },
      {
        annId: "20480",
        date: {
          day: 21,
          month: 9,
          year: 1999,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213242",
        label: "2",
        multi: false,
        title: "Sailor Moon SuperS",
      },
      {
        annId: "20481",
        date: {
          day: 11,
          month: 1,
          year: 2000,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213266",
        label: "3",
        multi: false,
        title: "Sailor Moon SuperS",
      },
      {
        annId: "20482",
        date: {
          day: 15,
          month: 8,
          year: 2000,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9781892213396",
        label: "4",
        multi: false,
        title: "Sailor Moon SuperS",
      },
    ],
    staff: ["Naoko Takeuchi"],
    synopsis:
      "Usagi Tsukino is a normal girl until she meets up with Luna, a talking cat, who tells her that she is Sailor Moon. As Sailor Moon, Usagi must fight evils and enforce justice, in the name of the Moon and the mysterious Moon Princess. She meets other people destined to be senshi, and together, they fight the forces of evil.",
    title: "Sailor Moon",
    url: "https://www.animenewsnetwork.com/encyclopedia/manga.php?id=1578",
  },
  series: {
    title: "Sailor Moon",
    altTitles: [
      "Bishōjo Senshi Sailor Moon",
      "Pretty Guardian Sailor Moon",
      "美少女戦士セーラームーン",
    ],
  },
  release: {
    isbn13: "9781612620022",
    binding: "paperback",
    format: "physical",
    language: "en",
  },
};

export const cirque = {
  source: {
    annId: "57382",
    date: {
      day: 22,
      month: 2,
      year: 2022,
    },
    editionLineHint: true,
    format: "physical",
    isbn13: "9781975321581",
    kind: "annRelease",
    label: "5",
    mangaId: "8436",
    multi: false,
    page: {
      date: {
        day: 22,
        month: 2,
        year: 2022,
      },
      distributor: "Yen Press",
      distributorId: "6612",
      fetchedAt: 1790505063071,
      isbn10: "1975321588",
      isbn13: "9781975321581",
      mangaId: "8436",
      priceCents: 2400,
      status: "ok",
      title: "Cirque Du Freak [Omnibus Edition]",
      volume: "GN 5",
    },
    title: "Cirque Du Freak [Omnibus Edition]",
    url: "https://www.animenewsnetwork.com/encyclopedia/releases.php?id=57382",
  } satisfies AnnReleaseSnapshot,
  parent: {
    altTitles: ["Darren Shan", "The Saga of Darren Shan", "ダレン・シャン"],
    credits: [
      {
        name: "Darren Shan",
        personId: "66431",
        task: "Original creator",
      },
      {
        name: "Takahiro Arai",
        personId: "66432",
        task: "Art",
      },
    ],
    id: "8436",
    kind: "annManga",
    releases: [
      {
        annId: "13691",
        date: {
          day: 30,
          month: 6,
          year: 2009,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780759530416",
        label: "1",
        multi: false,
        title: "Cirque du Freak",
      },
      {
        annId: "14445",
        date: {
          day: 31,
          month: 8,
          year: 2009,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780759530386",
        label: "2",
        multi: false,
        title: "Cirque du Freak - The Vampire's Assistant",
      },
      {
        annId: "14446",
        date: {
          day: 31,
          month: 10,
          year: 2009,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780759530430",
        label: "3",
        multi: false,
        title: "Cirque du Freak - Tunnels of Blood",
      },
      {
        annId: "15086",
        date: {
          day: 31,
          month: 1,
          year: 2010,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780759530393",
        label: "4",
        multi: false,
        title: "Cirque du Freak - Vampire Mountain",
      },
      {
        annId: "16314",
        date: {
          day: 20,
          month: 4,
          year: 2010,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780759530423",
        label: "5",
        multi: false,
        title: "Cirque du Freak - Trials of Death",
      },
      {
        annId: "17187",
        date: {
          day: 27,
          month: 7,
          year: 2010,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780759530409",
        label: "6",
        multi: false,
        title: "Cirque du Freak - The Vampire Prince",
      },
      {
        annId: "16407",
        date: {
          day: 26,
          month: 10,
          year: 2010,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780759530379",
        label: "7",
        multi: false,
        title: "Cirque du Freak - Hunters of the Dusk",
      },
      {
        annId: "17605",
        date: {
          day: 22,
          month: 3,
          year: 2011,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780316176088",
        label: "8",
        multi: false,
        title: "Cirque du Freak - Allies of the Night",
      },
      {
        annId: "17788",
        date: {
          day: 24,
          month: 5,
          year: 2011,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780316176064",
        label: "9",
        multi: false,
        title: "Cirque du Freak - Killers of the Dawn",
      },
      {
        annId: "17787",
        date: {
          day: 19,
          month: 7,
          year: 2011,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780316176071",
        label: "10",
        multi: false,
        title: "Cirque du Freak - The Lake of Souls",
      },
      {
        annId: "19220",
        date: {
          day: 25,
          month: 10,
          year: 2011,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780316182843",
        label: "11",
        multi: false,
        title: "Cirque du Freak - Lord of the Shadows",
      },
      {
        annId: "19223",
        date: {
          day: 24,
          month: 1,
          year: 2012,
        },
        editionLineHint: false,
        format: "physical",
        isbn13: "9780316182836",
        label: "12",
        multi: false,
        title: "Cirque du Freak - Sons of Destiny",
      },
      {
        annId: "57378",
        date: {
          day: 26,
          month: 1,
          year: 2021,
        },
        editionLineHint: true,
        format: "physical",
        isbn13: "9781975320058",
        label: "1",
        multi: false,
        title: "Cirque Du Freak [Omnibus Edition]",
      },
      {
        annId: "57379",
        date: {
          day: 20,
          month: 4,
          year: 2021,
        },
        editionLineHint: true,
        format: "physical",
        isbn13: "9781975321543",
        label: "2",
        multi: false,
        title: "Cirque Du Freak [Omnibus Edition]",
      },
      {
        annId: "57380",
        date: {
          day: 27,
          month: 7,
          year: 2021,
        },
        editionLineHint: true,
        format: "physical",
        isbn13: "9781975321550",
        label: "3",
        multi: false,
        title: "Cirque Du Freak [Omnibus Edition]",
      },
      {
        annId: "57381",
        date: {
          day: 9,
          month: 11,
          year: 2021,
        },
        editionLineHint: true,
        format: "physical",
        isbn13: "9781975321628",
        label: "4",
        multi: false,
        title: "Cirque Du Freak [Omnibus Edition]",
      },
      {
        annId: "57382",
        date: {
          day: 22,
          month: 2,
          year: 2022,
        },
        editionLineHint: true,
        format: "physical",
        isbn13: "9781975321581",
        label: "5",
        multi: false,
        title: "Cirque Du Freak [Omnibus Edition]",
      },
      {
        annId: "57383",
        date: {
          day: 24,
          month: 5,
          year: 2022,
        },
        editionLineHint: true,
        format: "physical",
        isbn13: "9781975321598",
        label: "6",
        multi: false,
        title: "Cirque Du Freak [Omnibus Edition]",
      },
    ],
    staff: ["Darren Shan", "Takahiro Arai"],
    synopsis:
      "Darren Shan is an ordinary boy living an ordinary life until he receives a flyer for the freak show \"Cirque du Freak\". When the preformance is over, he overhears a conversation between his friend Steve Leopard and one of the preformers, Mr. Crepsley, only to discover that the odd perfomer is a vampire. In order to save Steve's life, Darren must become Mr. Crepsley's Half vampire assistant. Now he must travel the world to regain his humanity.",
    title: "Cirque du Freak",
    url: "https://www.animenewsnetwork.com/encyclopedia/manga.php?id=8436",
  },
  series: {
    title: "Cirque Du Freak: The Manga",
    altTitles: ["Cirque du Freak", "Darren Shan", "The Saga of Darren Shan", "ダレン・シャン"],
  },
  release: {
    isbn13: "9781975321581",
    binding: "paperback",
    format: "physical",
    language: "en",
  },
};
