/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaimUsernameRouteImport } from './routes/claim-username'
import { Route as MeRouteImport } from './routes/me'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IsbnIsbnRouteImport } from './routes/isbn.$isbn'
import { Route as MeIndexRouteImport } from './routes/me.index'
import { Route as ModRolesRouteImport } from './routes/mod.roles'
import { Route as PublisherSlugRouteImport } from './routes/publisher.$slug'
import { Route as ReleasesIndexRouteImport } from './routes/releases.index'
import { Route as ReleasesMonthRouteImport } from './routes/releases.$month'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as BundlePublicIdIndexRouteImport } from './routes/bundle.$publicId.index'
import { Route as BundlePublicIdSlugRouteImport } from './routes/bundle.$publicId.$slug'
import { Route as EditionPublicIdIndexRouteImport } from './routes/edition.$publicId.index'
import { Route as EditionPublicIdSlugRouteImport } from './routes/edition.$publicId.$slug'
import { Route as SeriesPublicIdIndexRouteImport } from './routes/series.$publicId.index'
import { Route as SeriesPublicIdSlugRouteImport } from './routes/series.$publicId.$slug'
import { Route as VolumePublicIdIndexRouteImport } from './routes/volume.$publicId.index'
import { Route as VolumePublicIdSlugRouteImport } from './routes/volume.$publicId.$slug'
import { Route as ModEditTypeKeyRouteImport } from './routes/mod.edit.$type.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimUsernameRoute = ClaimUsernameRouteImport.update({
  id: '/claim-username',
  path: '/claim-username',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IsbnIsbnRoute = IsbnIsbnRouteImport.update({
  id: '/isbn/$isbn',
  path: '/isbn/$isbn',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const ModRolesRoute = ModRolesRouteImport.update({
  id: '/mod/roles',
  path: '/mod/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherSlugRoute = PublisherSlugRouteImport.update({
  id: '/publisher/$slug',
  path: '/publisher/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesMonthRoute = ReleasesMonthRouteImport.update({
  id: '/releases/$month',
  path: '/releases/$month',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlePublicIdIndexRoute = BundlePublicIdIndexRouteImport.update({
  id: '/bundle/$publicId/',
  path: '/bundle/$publicId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlePublicIdSlugRoute = BundlePublicIdSlugRouteImport.update({
  id: '/bundle/$publicId/$slug',
  path: '/bundle/$publicId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionPublicIdIndexRoute = EditionPublicIdIndexRouteImport.update({
  id: '/edition/$publicId/',
  path: '/edition/$publicId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionPublicIdSlugRoute = EditionPublicIdSlugRouteImport.update({
  id: '/edition/$publicId/$slug',
  path: '/edition/$publicId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesPublicIdIndexRoute = SeriesPublicIdIndexRouteImport.update({
  id: '/series/$publicId/',
  path: '/series/$publicId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesPublicIdSlugRoute = SeriesPublicIdSlugRouteImport.update({
  id: '/series/$publicId/$slug',
  path: '/series/$publicId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumePublicIdIndexRoute = VolumePublicIdIndexRouteImport.update({
  id: '/volume/$publicId/',
  path: '/volume/$publicId/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolumePublicIdSlugRoute = VolumePublicIdSlugRouteImport.update({
  id: '/volume/$publicId/$slug',
  path: '/volume/$publicId/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ModEditTypeKeyRoute = ModEditTypeKeyRouteImport.update({
  id: '/mod/edit/$type/$key',
  path: '/mod/edit/$type/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim-username': typeof ClaimUsernameRoute
  '/me': typeof MeRouteWithChildren
  '/search': typeof SearchRoute
  '/isbn/$isbn': typeof IsbnIsbnRoute
  '/mod/roles': typeof ModRolesRoute
  '/publisher/$slug': typeof PublisherSlugRoute
  '/releases/$month': typeof ReleasesMonthRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/me/': typeof MeIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/bundle/$publicId/$slug': typeof BundlePublicIdSlugRoute
  '/edition/$publicId/$slug': typeof EditionPublicIdSlugRoute
  '/series/$publicId/$slug': typeof SeriesPublicIdSlugRoute
  '/volume/$publicId/$slug': typeof VolumePublicIdSlugRoute
  '/bundle/$publicId/': typeof BundlePublicIdIndexRoute
  '/edition/$publicId/': typeof EditionPublicIdIndexRoute
  '/series/$publicId/': typeof SeriesPublicIdIndexRoute
  '/volume/$publicId/': typeof VolumePublicIdIndexRoute
  '/mod/edit/$type/$key': typeof ModEditTypeKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim-username': typeof ClaimUsernameRoute
  '/search': typeof SearchRoute
  '/isbn/$isbn': typeof IsbnIsbnRoute
  '/mod/roles': typeof ModRolesRoute
  '/publisher/$slug': typeof PublisherSlugRoute
  '/releases/$month': typeof ReleasesMonthRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/me': typeof MeIndexRoute
  '/releases': typeof ReleasesIndexRoute
  '/bundle/$publicId/$slug': typeof BundlePublicIdSlugRoute
  '/edition/$publicId/$slug': typeof EditionPublicIdSlugRoute
  '/series/$publicId/$slug': typeof SeriesPublicIdSlugRoute
  '/volume/$publicId/$slug': typeof VolumePublicIdSlugRoute
  '/bundle/$publicId': typeof BundlePublicIdIndexRoute
  '/edition/$publicId': typeof EditionPublicIdIndexRoute
  '/series/$publicId': typeof SeriesPublicIdIndexRoute
  '/volume/$publicId': typeof VolumePublicIdIndexRoute
  '/mod/edit/$type/$key': typeof ModEditTypeKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim-username': typeof ClaimUsernameRoute
  '/me': typeof MeRouteWithChildren
  '/search': typeof SearchRoute
  '/isbn/$isbn': typeof IsbnIsbnRoute
  '/mod/roles': typeof ModRolesRoute
  '/publisher/$slug': typeof PublisherSlugRoute
  '/releases/$month': typeof ReleasesMonthRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/me/': typeof MeIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/bundle/$publicId/$slug': typeof BundlePublicIdSlugRoute
  '/edition/$publicId/$slug': typeof EditionPublicIdSlugRoute
  '/series/$publicId/$slug': typeof SeriesPublicIdSlugRoute
  '/volume/$publicId/$slug': typeof VolumePublicIdSlugRoute
  '/bundle/$publicId/': typeof BundlePublicIdIndexRoute
  '/edition/$publicId/': typeof EditionPublicIdIndexRoute
  '/series/$publicId/': typeof SeriesPublicIdIndexRoute
  '/volume/$publicId/': typeof VolumePublicIdIndexRoute
  '/mod/edit/$type/$key': typeof ModEditTypeKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim-username'
    | '/me'
    | '/search'
    | '/isbn/$isbn'
    | '/mod/roles'
    | '/publisher/$slug'
    | '/releases/$month'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/me/'
    | '/releases/'
    | '/bundle/$publicId/$slug'
    | '/edition/$publicId/$slug'
    | '/series/$publicId/$slug'
    | '/volume/$publicId/$slug'
    | '/bundle/$publicId/'
    | '/edition/$publicId/'
    | '/series/$publicId/'
    | '/volume/$publicId/'
    | '/mod/edit/$type/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim-username'
    | '/search'
    | '/isbn/$isbn'
    | '/mod/roles'
    | '/publisher/$slug'
    | '/releases/$month'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/me'
    | '/releases'
    | '/bundle/$publicId/$slug'
    | '/edition/$publicId/$slug'
    | '/series/$publicId/$slug'
    | '/volume/$publicId/$slug'
    | '/bundle/$publicId'
    | '/edition/$publicId'
    | '/series/$publicId'
    | '/volume/$publicId'
    | '/mod/edit/$type/$key'
  id:
    | '__root__'
    | '/'
    | '/claim-username'
    | '/me'
    | '/search'
    | '/isbn/$isbn'
    | '/mod/roles'
    | '/publisher/$slug'
    | '/releases/$month'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/me/'
    | '/releases/'
    | '/bundle/$publicId/$slug'
    | '/edition/$publicId/$slug'
    | '/series/$publicId/$slug'
    | '/volume/$publicId/$slug'
    | '/bundle/$publicId/'
    | '/edition/$publicId/'
    | '/series/$publicId/'
    | '/volume/$publicId/'
    | '/mod/edit/$type/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimUsernameRoute: typeof ClaimUsernameRoute
  MeRoute: typeof MeRouteWithChildren
  SearchRoute: typeof SearchRoute
  IsbnIsbnRoute: typeof IsbnIsbnRoute
  ModRolesRoute: typeof ModRolesRoute
  PublisherSlugRoute: typeof PublisherSlugRoute
  ReleasesMonthRoute: typeof ReleasesMonthRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
  BundlePublicIdSlugRoute: typeof BundlePublicIdSlugRoute
  EditionPublicIdSlugRoute: typeof EditionPublicIdSlugRoute
  SeriesPublicIdSlugRoute: typeof SeriesPublicIdSlugRoute
  VolumePublicIdSlugRoute: typeof VolumePublicIdSlugRoute
  BundlePublicIdIndexRoute: typeof BundlePublicIdIndexRoute
  EditionPublicIdIndexRoute: typeof EditionPublicIdIndexRoute
  SeriesPublicIdIndexRoute: typeof SeriesPublicIdIndexRoute
  VolumePublicIdIndexRoute: typeof VolumePublicIdIndexRoute
  ModEditTypeKeyRoute: typeof ModEditTypeKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-username': {
      id: '/claim-username'
      path: '/claim-username'
      fullPath: '/claim-username'
      preLoaderRoute: typeof ClaimUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isbn/$isbn': {
      id: '/isbn/$isbn'
      path: '/isbn/$isbn'
      fullPath: '/isbn/$isbn'
      preLoaderRoute: typeof IsbnIsbnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/mod/roles': {
      id: '/mod/roles'
      path: '/mod/roles'
      fullPath: '/mod/roles'
      preLoaderRoute: typeof ModRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/$slug': {
      id: '/publisher/$slug'
      path: '/publisher/$slug'
      fullPath: '/publisher/$slug'
      preLoaderRoute: typeof PublisherSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/': {
      id: '/releases/'
      path: '/releases'
      fullPath: '/releases/'
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$month': {
      id: '/releases/$month'
      path: '/releases/$month'
      fullPath: '/releases/$month'
      preLoaderRoute: typeof ReleasesMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle/$publicId/': {
      id: '/bundle/$publicId/'
      path: '/bundle/$publicId'
      fullPath: '/bundle/$publicId/'
      preLoaderRoute: typeof BundlePublicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle/$publicId/$slug': {
      id: '/bundle/$publicId/$slug'
      path: '/bundle/$publicId/$slug'
      fullPath: '/bundle/$publicId/$slug'
      preLoaderRoute: typeof BundlePublicIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edition/$publicId/': {
      id: '/edition/$publicId/'
      path: '/edition/$publicId'
      fullPath: '/edition/$publicId/'
      preLoaderRoute: typeof EditionPublicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edition/$publicId/$slug': {
      id: '/edition/$publicId/$slug'
      path: '/edition/$publicId/$slug'
      fullPath: '/edition/$publicId/$slug'
      preLoaderRoute: typeof EditionPublicIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$publicId/': {
      id: '/series/$publicId/'
      path: '/series/$publicId'
      fullPath: '/series/$publicId/'
      preLoaderRoute: typeof SeriesPublicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$publicId/$slug': {
      id: '/series/$publicId/$slug'
      path: '/series/$publicId/$slug'
      fullPath: '/series/$publicId/$slug'
      preLoaderRoute: typeof SeriesPublicIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume/$publicId/': {
      id: '/volume/$publicId/'
      path: '/volume/$publicId'
      fullPath: '/volume/$publicId/'
      preLoaderRoute: typeof VolumePublicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volume/$publicId/$slug': {
      id: '/volume/$publicId/$slug'
      path: '/volume/$publicId/$slug'
      fullPath: '/volume/$publicId/$slug'
      preLoaderRoute: typeof VolumePublicIdSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mod/edit/$type/$key': {
      id: '/mod/edit/$type/$key'
      path: '/mod/edit/$type/$key'
      fullPath: '/mod/edit/$type/$key'
      preLoaderRoute: typeof ModEditTypeKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MeRouteChildren {
  MeIndexRoute: typeof MeIndexRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeIndexRoute: MeIndexRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimUsernameRoute: ClaimUsernameRoute,
  MeRoute: MeRouteWithChildren,
  SearchRoute: SearchRoute,
  IsbnIsbnRoute: IsbnIsbnRoute,
  ModRolesRoute: ModRolesRoute,
  PublisherSlugRoute: PublisherSlugRoute,
  ReleasesMonthRoute: ReleasesMonthRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
  BundlePublicIdSlugRoute: BundlePublicIdSlugRoute,
  EditionPublicIdSlugRoute: EditionPublicIdSlugRoute,
  SeriesPublicIdSlugRoute: SeriesPublicIdSlugRoute,
  VolumePublicIdSlugRoute: VolumePublicIdSlugRoute,
  BundlePublicIdIndexRoute: BundlePublicIdIndexRoute,
  EditionPublicIdIndexRoute: EditionPublicIdIndexRoute,
  SeriesPublicIdIndexRoute: SeriesPublicIdIndexRoute,
  VolumePublicIdIndexRoute: VolumePublicIdIndexRoute,
  ModEditTypeKeyRoute: ModEditTypeKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
